package com.example.data

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

@Database(
    entities = [
        WordItem::class, WrongWordItem::class, Level::class, UserStats::class, PracticeSession::class,
        HolidayHomeworkPack::class, HolidayTask::class, HolidayTaskCheckIn::class, HolidayWorkSession::class,
        HolidayStudyMaterial::class, HolidayMaterialProgress::class, HolidayRecitationRecord::class, HolidayDictationRecord::class,
        PlayerProfile::class, LocalAccount::class, PetBinding::class, LocalSession::class,
        PlayerBrushConfig::class, MonsterCodexEntry::class, LootDropRecord::class, AchievementRecord::class,
        PlayerInventoryItem::class
    ],
    version = 22,
    exportSchema = false
)
@TypeConverters(PracticeSessionConverters::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun wordDao(): WordDao
    abstract fun wrongWordDao(): WrongWordDao
    abstract fun levelDao(): LevelDao
    abstract fun userStatsDao(): UserStatsDao
    abstract fun practiceSessionDao(): PracticeSessionDao
    abstract fun holidayHomeworkDao(): HolidayHomeworkDao
    abstract fun playerProfileDao(): PlayerProfileDao
    abstract fun localAccountDao(): LocalAccountDao
    abstract fun petBindingDao(): PetBindingDao
    abstract fun localSessionDao(): LocalSessionDao
    abstract fun playerBrushConfigDao(): PlayerBrushConfigDao
    abstract fun monsterCodexDao(): MonsterCodexDao
    abstract fun lootDropDao(): LootDropDao
    abstract fun achievementDao(): AchievementDao
    abstract fun playerInventoryDao(): PlayerInventoryDao


    companion object {
        @Volatile
        private var INSTANCE: AppDatabase? = null

        private val MIGRATION_3_4 = object : Migration(3, 4) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE levels ADD COLUMN sortIndex INTEGER NOT NULL DEFAULT 0")
                db.execSQL("ALTER TABLE levels ADD COLUMN sourcePackId TEXT DEFAULT NULL")
            }
        }

        private val MIGRATION_4_5 = object : Migration(4, 5) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE words ADD COLUMN promptMode TEXT NOT NULL DEFAULT 'FULL_WORD'")
                db.execSQL("ALTER TABLE words ADD COLUMN hiddenIndicesStr TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE words ADD COLUMN visiblePrompt TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE words ADD COLUMN ttsPrompt TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE words ADD COLUMN contextText TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE words ADD COLUMN targetAnswer TEXT NOT NULL DEFAULT ''")
            }
        }

        private val MIGRATION_5_6 = object : Migration(5, 6) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE levels ADD COLUMN practiceLimitMode TEXT NOT NULL DEFAULT 'USE_GLOBAL'")
                db.execSQL("ALTER TABLE levels ADD COLUMN fixedQuestionCount INTEGER DEFAULT NULL")
            }
        }

        private val MIGRATION_6_7 = object : Migration(6, 7) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE words ADD COLUMN clueText TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE words ADD COLUMN meaningHint TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE words ADD COLUMN exampleText TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE words ADD COLUMN sourceLesson TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE words ADD COLUMN promptAutoGenerated INTEGER NOT NULL DEFAULT 1")
                db.execSQL("ALTER TABLE words ADD COLUMN promptManuallyEdited INTEGER NOT NULL DEFAULT 0")
                db.execSQL("ALTER TABLE words ADD COLUMN promptQuality TEXT NOT NULL DEFAULT 'GOOD'")

                db.execSQL("ALTER TABLE user_stats ADD COLUMN allowStudentViewMeaning TEXT NOT NULL DEFAULT 'AFTER_ERROR'")
            }
        }

        private val MIGRATION_7_8 = object : Migration(7, 8) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE words ADD COLUMN visibilityPolicy TEXT NOT NULL DEFAULT 'TEST_SAFE'")
            }
        }

        private val MIGRATION_8_9 = object : Migration(8, 9) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `holiday_homework_packs` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `packId` TEXT NOT NULL,
                        `title` TEXT NOT NULL,
                        `subtitle` TEXT NOT NULL,
                        `grade` TEXT NOT NULL,
                        `semester` TEXT NOT NULL,
                        `sourceType` TEXT NOT NULL,
                        `description` TEXT NOT NULL,
                        `startDate` TEXT,
                        `endDate` TEXT,
                        `isInstalled` INTEGER NOT NULL DEFAULT 0,
                        `createdAt` INTEGER NOT NULL,
                        `updatedAt` INTEGER NOT NULL
                    )
                """.trimIndent())

                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `holiday_tasks` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `packId` TEXT NOT NULL,
                        `subject` TEXT NOT NULL,
                        `category` TEXT NOT NULL,
                        `title` TEXT NOT NULL,
                        `description` TEXT NOT NULL,
                        `requirement` TEXT NOT NULL,
                        `taskType` TEXT NOT NULL,
                        `totalCount` INTEGER NOT NULL,
                        `completedCount` INTEGER NOT NULL,
                        `unitLabel` TEXT,
                        `frequencyRule` TEXT,
                        `linkedLevelId` INTEGER,
                        `sortOrder` INTEGER NOT NULL,
                        `isRequired` INTEGER NOT NULL,
                        `tierRule` TEXT NOT NULL DEFAULT 'ALL',
                        `status` TEXT NOT NULL DEFAULT 'PENDING',
                        `isRecited` INTEGER NOT NULL DEFAULT 0,
                        `isMemorized` INTEGER NOT NULL DEFAULT 0,
                        `isDraftDone` INTEGER NOT NULL DEFAULT 0,
                        `isFinalWritten` INTEGER NOT NULL DEFAULT 0,
                        `isParentConfirmed` INTEGER NOT NULL DEFAULT 0,
                        `createdAt` INTEGER NOT NULL,
                        `updatedAt` INTEGER NOT NULL
                    )
                """.trimIndent())

                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `holiday_task_check_ins` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `taskId` INTEGER NOT NULL,
                        `date` TEXT NOT NULL,
                        `progressDelta` INTEGER NOT NULL,
                        `note` TEXT,
                        `parentConfirmed` INTEGER NOT NULL DEFAULT 0,
                        `createdAt` INTEGER NOT NULL
                    )
                """.trimIndent())

                db.execSQL("ALTER TABLE user_stats ADD COLUMN mathGradeTier TEXT NOT NULL DEFAULT 'ABOVE_90'")
                db.execSQL("ALTER TABLE user_stats ADD COLUMN englishGradeTier TEXT NOT NULL DEFAULT 'ABOVE_88'")
            }
        }

        private val MIGRATION_9_10 = object : Migration(9, 10) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `holiday_work_sessions` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `taskId` INTEGER NOT NULL,
                        `packId` TEXT NOT NULL,
                        `subject` TEXT NOT NULL,
                        `taskType` TEXT NOT NULL,
                        `startedAt` INTEGER NOT NULL,
                        `endedAt` INTEGER,
                        `durationMinutes` INTEGER NOT NULL,
                        `progressDelta` INTEGER NOT NULL,
                        `note` TEXT,
                        `titleInput` TEXT,
                        `extraJson` TEXT,
                        `parentConfirmed` INTEGER NOT NULL DEFAULT 0,
                        `createdAt` INTEGER NOT NULL
                    )
                """.trimIndent())
            }
        }

        private val MIGRATION_10_11 = object : Migration(10, 11) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `holiday_study_materials` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `packId` TEXT NOT NULL,
                        `materialId` TEXT NOT NULL,
                        `subject` TEXT NOT NULL,
                        `grade` TEXT NOT NULL,
                        `semester` TEXT NOT NULL,
                        `unitName` TEXT,
                        `lessonNo` TEXT,
                        `lessonTitle` TEXT NOT NULL,
                        `materialType` TEXT NOT NULL,
                        `title` TEXT NOT NULL,
                        `author` TEXT,
                        `fullText` TEXT NOT NULL,
                        `sectionsJson` TEXT,
                        `annotationJson` TEXT,
                        `sourceNote` TEXT NOT NULL,
                        `sourcePage` TEXT,
                        `memorizeRequired` INTEGER NOT NULL DEFAULT 1,
                        `dictationRequired` INTEGER NOT NULL DEFAULT 1,
                        `copyRequired` INTEGER NOT NULL DEFAULT 0,
                        `isPrivate` INTEGER NOT NULL DEFAULT 1,
                        `createdAt` INTEGER NOT NULL
                    )
                """.trimIndent())

                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `holiday_material_progress` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `materialId` TEXT NOT NULL,
                        `taskId` INTEGER,
                        `readCount` INTEGER NOT NULL DEFAULT 0,
                        `reciteStatus` TEXT NOT NULL DEFAULT 'NOT_STARTED',
                        `dictationStatus` TEXT NOT NULL DEFAULT 'NOT_STARTED',
                        `copyCount` INTEGER NOT NULL DEFAULT 0,
                        `parentConfirmed` INTEGER NOT NULL DEFAULT 0,
                        `updatedAt` INTEGER NOT NULL
                    )
                """.trimIndent())

                try {
                    db.execSQL("ALTER TABLE holiday_tasks ADD COLUMN linkedMaterialIdsStr TEXT DEFAULT NULL")
                    db.execSQL("ALTER TABLE holiday_tasks ADD COLUMN materialRunnerType TEXT DEFAULT NULL")
                } catch (e: Exception) {
                    e.printStackTrace()
                }
            }
        }

        private val MIGRATION_11_12 = object : Migration(11, 12) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `holiday_recitation_records` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `materialId` TEXT NOT NULL,
                        `materialTitle` TEXT NOT NULL,
                        `audioPath` TEXT NOT NULL,
                        `durationMs` INTEGER NOT NULL,
                        `mode` TEXT NOT NULL,
                        `parentStatus` TEXT NOT NULL DEFAULT 'PENDING',
                        `parentComment` TEXT,
                        `createdAt` INTEGER NOT NULL
                    )
                """.trimIndent())

                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `holiday_dictation_records` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `materialId` TEXT NOT NULL,
                        `materialTitle` TEXT NOT NULL,
                        `sentenceIndex` INTEGER NOT NULL,
                        `standardText` TEXT NOT NULL,
                        `handwrittenStrokesJson` TEXT NOT NULL,
                        `status` TEXT NOT NULL DEFAULT 'PENDING',
                        `durationMs` INTEGER NOT NULL DEFAULT 0,
                        `createdAt` INTEGER NOT NULL
                    )
                """.trimIndent())
            }
        }

        private val MIGRATION_12_13 = object : Migration(12, 13) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `player_profile` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `playerName` TEXT NOT NULL,
                        `avatarId` INTEGER NOT NULL,
                        `petId` TEXT,
                        `level` INTEGER NOT NULL DEFAULT 1,
                        `exp` INTEGER NOT NULL DEFAULT 0,
                        `coins` INTEGER NOT NULL DEFAULT 0,
                        `totalStudyDays` INTEGER NOT NULL DEFAULT 0,
                        `streakDays` INTEGER NOT NULL DEFAULT 0,
                        `highestCombo` INTEGER NOT NULL DEFAULT 0,
                        `createdAt` INTEGER NOT NULL,
                        `updatedAt` INTEGER NOT NULL
                    )
                """.trimIndent())
            }
        }

        private val MIGRATION_13_14 = object : Migration(13, 14) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // Alter player_profile table to add new columns
                try {
                    db.execSQL("ALTER TABLE player_profile ADD COLUMN accountId INTEGER NOT NULL DEFAULT 0")
                    db.execSQL("ALTER TABLE player_profile ADD COLUMN isSelected INTEGER NOT NULL DEFAULT 0")
                    db.execSQL("ALTER TABLE player_profile ADD COLUMN isDeleted INTEGER NOT NULL DEFAULT 0")
                } catch (e: Exception) {
                    e.printStackTrace()
                }

                // Create local_accounts table
                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `local_accounts` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `accountName` TEXT NOT NULL,
                        `pinHash` TEXT,
                        `createdAt` INTEGER NOT NULL,
                        `updatedAt` INTEGER NOT NULL,
                        `lastLoginAt` INTEGER NOT NULL,
                        `isActive` INTEGER NOT NULL DEFAULT 1,
                        `isDeleted` INTEGER NOT NULL DEFAULT 0
                    )
                """.trimIndent())

                // Create pet_bindings table
                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `pet_bindings` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `accountId` INTEGER NOT NULL,
                        `playerId` INTEGER NOT NULL,
                        `petId` TEXT NOT NULL,
                        `petName` TEXT NOT NULL,
                        `level` INTEGER NOT NULL DEFAULT 1,
                        `intimacy` INTEGER NOT NULL DEFAULT 100,
                        `isActive` INTEGER NOT NULL DEFAULT 1,
                        `createdAt` INTEGER NOT NULL,
                        `updatedAt` INTEGER NOT NULL
                    )
                """.trimIndent())

                // Create local_sessions table
                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `local_sessions` (
                        `id` INTEGER PRIMARY KEY NOT NULL,
                        `currentAccountId` INTEGER,
                        `currentPlayerId` INTEGER,
                        `lastRoute` TEXT,
                        `updatedAt` INTEGER NOT NULL
                    )
                """.trimIndent())
            }
        }

        private val MIGRATION_14_15 = object : Migration(14, 15) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // Version 15 empty migration placeholder
            }
        }

        private val MIGRATION_15_16 = object : Migration(15, 16) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // Add columns to pet_bindings
                try {
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN lifeStage TEXT NOT NULL DEFAULT 'HATCHLING'")
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN customName TEXT DEFAULT NULL")
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN hatchProgress INTEGER NOT NULL DEFAULT 0")
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN growthExp INTEGER NOT NULL DEFAULT 0")
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN spiritPower INTEGER NOT NULL DEFAULT 0")
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN isSleeping INTEGER NOT NULL DEFAULT 0")
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN hatchedAt INTEGER DEFAULT NULL")
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN lastFedAt INTEGER DEFAULT NULL")
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN fedCountToday INTEGER NOT NULL DEFAULT 0")
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN lastFedDay TEXT DEFAULT NULL")
                } catch (e: Exception) {
                    e.printStackTrace()
                }

                // Add columns to player_profile
                try {
                    db.execSQL("ALTER TABLE player_profile ADD COLUMN equippedBrushId TEXT NOT NULL DEFAULT 'default_black'")
                    db.execSQL("ALTER TABLE player_profile ADD COLUMN unlockedBrushIds TEXT NOT NULL DEFAULT 'default_black,practice_wood'")
                } catch (e: Exception) {
                    e.printStackTrace()
                }
            }
        }

        private val MIGRATION_16_17 = object : Migration(16, 17) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `player_brush_configs` (
                        `configId` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `accountId` INTEGER NOT NULL,
                        `playerId` INTEGER NOT NULL,
                        `brushId` TEXT NOT NULL,
                        `baseWidth` REAL NOT NULL,
                        `minWidth` REAL NOT NULL,
                        `maxWidth` REAL NOT NULL,
                        `pressureSensitivity` REAL NOT NULL,
                        `speedSensitivity` REAL NOT NULL,
                        `smoothing` REAL NOT NULL,
                        `opacity` REAL NOT NULL,
                        `glowRadius` REAL NOT NULL,
                        `particleDensity` REAL NOT NULL,
                        `effectIntensity` REAL NOT NULL,
                        `colorHex` TEXT NOT NULL,
                        `usageMode` TEXT NOT NULL,
                        `updatedAt` INTEGER NOT NULL
                    )
                """.trimIndent())
                db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_player_brush_configs_playerId_brushId` ON `player_brush_configs` (`playerId`, `brushId`)")
            }
        }

        private val MIGRATION_17_18 = object : Migration(17, 18) {
            override fun migrate(db: SupportSQLiteDatabase) {
                try {
                    db.execSQL("ALTER TABLE player_brush_configs ADD COLUMN widthMode TEXT NOT NULL DEFAULT 'AUTO'")
                } catch (e: Exception) {
                    e.printStackTrace()
                }
            }
        }

        private val MIGRATION_18_19 = object : Migration(18, 19) {
            override fun migrate(db: SupportSQLiteDatabase) {
                try {
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN hunger INTEGER NOT NULL DEFAULT 100")
                    db.execSQL("ALTER TABLE pet_bindings ADD COLUMN discoveredType INTEGER NOT NULL DEFAULT 0")
                } catch (e: Exception) {
                    e.printStackTrace()
                }
            }
        }

        private val MIGRATION_19_20 = object : Migration(19, 20) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // Placeholder to prevent crash if jumping from v19
            }
        }

        private val MIGRATION_20_21 = object : Migration(20, 21) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `player_inventory_items` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `accountId` INTEGER NOT NULL,
                        `playerId` INTEGER NOT NULL,
                        `itemId` TEXT NOT NULL,
                        `itemType` TEXT NOT NULL,
                        `amount` INTEGER NOT NULL,
                        `isOwned` INTEGER NOT NULL DEFAULT 1,
                        `isEquipped` INTEGER NOT NULL DEFAULT 0,
                        `obtainedAt` INTEGER NOT NULL,
                        `updatedAt` INTEGER NOT NULL
                    )
                """.trimIndent())
                db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_player_inventory_items_playerId_itemId` ON `player_inventory_items` (`playerId`, `itemId`)")
            }
        }

        private val MIGRATION_21_22 = object : Migration(21, 22) {
            override fun migrate(db: SupportSQLiteDatabase) {
                try {
                    db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_player_inventory_items_playerId_itemId` ON `player_inventory_items` (`playerId`, `itemId`)")
                } catch (e: Exception) {
                    e.printStackTrace()
                }
            }
        }

        fun getDatabase(context: Context): AppDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    AppDatabase::class.java,
                    "word_crusade_database"
                )
                .addMigrations(
                    MIGRATION_3_4, MIGRATION_4_5, MIGRATION_5_6, MIGRATION_6_7, MIGRATION_7_8, 
                    MIGRATION_8_9, MIGRATION_9_10, MIGRATION_10_11, MIGRATION_11_12, MIGRATION_12_13, 
                    MIGRATION_13_14, MIGRATION_14_15, MIGRATION_15_16, MIGRATION_16_17, MIGRATION_17_18, MIGRATION_18_19,
                    MIGRATION_19_20, MIGRATION_20_21, MIGRATION_21_22
                )
                .fallbackToDestructiveMigration()
                .build()
                INSTANCE = instance
                instance
            }
        }
    }
}
