package com.example.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "words")
data class WordItem(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val text: String,
    val type: String, // 字, 词语, 成语, 句子, 古诗句, 课文重点句
    val unitName: String,
    val difficulty: String, // 普通, 易错, BOSS
    val promptMode: String = "FULL_WORD", // FULL_WORD, CLOZE_CHAR, CONTEXT_CLUE
    val hiddenIndicesStr: String = "", // e.g. "0" or "0,1"
    val visiblePrompt: String = "", // e.g. "__桃"
    val ttsPrompt: String = "", // e.g. "请写‘樱桃’的第一个字"
    val contextText: String = "", // e.g. "破晓的晓"
    val targetAnswer: String = "", // e.g. "樱"
    val clueText: String = "", // e.g. 白昼, 破晓
    val meaningHint: String = "", // e.g. 白天, 天刚亮的时候
    val exampleText: String = "",
    val sourceLesson: String = "",
    val promptAutoGenerated: Boolean = true,
    val promptManuallyEdited: Boolean = false,
    val promptQuality: String = "GOOD", // GOOD, NEED_CONTEXT, MANUAL, FALLBACK
    val visibilityPolicy: String = "TEST_SAFE" // TEST_SAFE, PRACTICE_HINT, REVIEW_ONLY
) {
    fun getEffectiveTargetAnswer(): String = if (targetAnswer.isNotBlank()) targetAnswer else text

    fun getEffectiveVisiblePrompt(isPracticeMode: Boolean = false): String {
        if (visibilityPolicy == "PRACTICE_HINT" || isPracticeMode) {
            return if (visiblePrompt.isNotBlank()) visiblePrompt else if (clueText.isNotBlank()) clueText else text
        }

        // TEST_SAFE 测验安全模式
        val target = getEffectiveTargetAnswer()
        val isSingleCharTarget = target.length == 1

        // 1. 如果 WordItem.visiblePrompt 非空：显示 maskTargetAnswerInPrompt(visiblePrompt, target)
        if (visiblePrompt.isNotBlank()) {
            return com.example.util.PromptSecurityUtil.maskTargetAnswerInPrompt(visiblePrompt, target)
        }

        // 2. 如果 visiblePrompt 为空，但 clueText 非空且 targetAnswer 是单字（或语境/填空模式）
        if (clueText.isNotBlank() && (isSingleCharTarget || promptMode == "CONTEXT_CLUE" || promptMode == "CLOZE_CHAR")) {
            return com.example.util.PromptSecurityUtil.buildSafeCluePrompt(clueText, target)
        }

        // 3. 如果 promptMode == CONTEXT_CLUE：不允许降级成“请根据语音写出词语”，除非 clueText 和 visiblePrompt 都为空
        if (promptMode == "CONTEXT_CLUE" && clueText.isNotBlank()) {
            return com.example.util.PromptSecurityUtil.buildSafeCluePrompt(clueText, target)
        }

        // 4. 只有在 FULL_WORD 且没有任何 visiblePrompt / clueText 时，才显示：请根据语音写出词语
        return "请根据语音写出词语"
    }

    fun getEffectiveSubPrompt(isPracticeMode: Boolean = false): String {
        if (visibilityPolicy == "PRACTICE_HINT" || isPracticeMode) {
            if (ttsPrompt.isNotBlank()) return ttsPrompt
            if (clueText.isNotBlank()) return "请写“${clueText}”的“${getEffectiveTargetAnswer()}”"
            return text
        }

        return if (promptMode == "FULL_WORD") {
            "请根据语音写出词语"
        } else {
            "请根据语音写出空缺的字"
        }
    }

    fun getFormattedAudioPrompt(): String {
        if (ttsPrompt.isNotBlank()) return ttsPrompt
        if (text.length == 1 && clueText.isNotBlank()) {
            return "请写“${clueText}”的“${text}”"
        }
        if (meaningHint.isNotBlank()) {
            return "请根据提示写出词语：${meaningHint}。${text}"
        }
        return "请写词语：$text"
    }

    fun getEffectiveTtsPrompt(): String = getFormattedAudioPrompt()
}

@Entity(tableName = "wrong_words")
data class WrongWordItem(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val text: String,
    val type: String,
    val unitName: String,
    val errorCount: Int,
    val lastErrorTime: Long,
    val isMastered: Boolean,
    val correctStreak: Int,
    val errorLevel: String = "重点" // 轻度, 重点
)

@Entity(tableName = "levels")
data class Level(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val unitName: String,
    val isUnlocked: Boolean,
    val isCompleted: Boolean,
    val isPreset: Boolean = false, // to identify our built-in 5 levels
    val wordIdsStr: String = "", // comma-separated WordItem IDs
    val sortIndex: Int = 0,
    val sourcePackId: String? = null,
    val practiceLimitMode: String = "USE_GLOBAL", // USE_GLOBAL, ALL, FIXED
    val fixedQuestionCount: Int? = null
)

@Entity(tableName = "user_stats")
data class UserStats(
    @PrimaryKey val id: Int = 1,
    val level: Int = 1,
    val experience: Int = 0,
    val coins: Int = 0,
    val totalAnswered: Int = 0,
    val correctCount: Int = 0,
    val wrongCount: Int = 0,
    val maxCorrectStreak: Int = 0,
    val dailyPracticeCount: Int = 0,
    val lastPracticeDate: String = "", // YYYY-MM-DD to track daily resets
    val timePerWord: Int = 30,
    val playCount: Int = 2,
    val allowExtraPlay: Boolean = true,
    val wordsPerLevel: Int = 8,
    val passRate: Int = 80,
    val gradingMode: String = "ASSISTED", // MANUAL, ASSISTED, AUTO
    val allowStudentViewMeaning: String = "AFTER_ERROR", // NEVER, AFTER_ERROR, ALWAYS
    val mathGradeTier: String = "ABOVE_90", // ABOVE_90, BELOW_90
    val englishGradeTier: String = "ABOVE_88" // ABOVE_88, BELOW_88
)

data class CharResult(
    val charIndex: Int,
    val pointsList: List<List<com.example.ui.PointData>>,
    val canvasWidth: Float,
    val canvasHeight: Float,
    val isBlank: Boolean,
    val expectedChar: String,
    val recognizedText: String,
    val candidates: List<String>,
    val confidenceLevel: String,
    val isLikelyCorrect: Boolean,
    val errorMessage: String? = null
)

data class QuestionResult(
    val questionId: Int,
    val correctText: String,
    val charResults: List<CharResult>,
    val autoResult: String, // CORRECT / PARTIAL / WRONG / NEED_REVIEW
    val finalResult: String, // CORRECT / PARTIAL / WRONG / NEED_REVIEW
    val needParentReview: Boolean,
    var parentOverrideResult: String? = null,
    var parentReviewedAt: Long? = null,
    val promptMode: String = "FULL_WORD",
    val hiddenIndicesStr: String = "",
    val visiblePrompt: String = "",
    val ttsPrompt: String = "",
    val targetAnswer: String = "",
    val clueText: String = "",
    val meaningHint: String = "",
    val errorReason: String = ""
) {
    fun getEffectiveVisiblePrompt(): String {
        return if (visiblePrompt.isNotBlank()) visiblePrompt else correctText
    }

    fun getEffectiveTtsPrompt(): String {
        return if (ttsPrompt.isNotBlank()) ttsPrompt else correctText
    }

    fun getEffectiveTargetAnswer(): String {
        return if (targetAnswer.isNotBlank()) targetAnswer else correctText
    }
}

@Entity(tableName = "player_brush_configs",
    indices = [androidx.room.Index(value = ["playerId", "brushId"], unique = true)]
)
data class PlayerBrushConfig(
    @PrimaryKey(autoGenerate = true) val configId: Long = 0,
    val accountId: Long,
    val playerId: Long,
    val brushId: String,
    val baseWidth: Float = 12f,
    val minWidth: Float = 4f,
    val maxWidth: Float = 24f,
    val pressureSensitivity: Float = 1.0f,
    val speedSensitivity: Float = 1.0f,
    val smoothing: Float = 0.5f,
    val opacity: Float = 1.0f,
    val glowRadius: Float = 0f,
    val particleDensity: Float = 0f,
    val effectIntensity: Float = 1.0f,
    val colorHex: String = "#000000",
    val usageMode: String = "TEST_SAFE", // TEST_SAFE, PRACTICE_FUN, SHOWCASE
    val widthMode: String = "AUTO", // AUTO, FORCE_SPEED, FORCE_PRESSURE, FIXED
    val updatedAt: Long = System.currentTimeMillis()
)

@Entity(tableName = "practice_sessions")
data class PracticeSession(
    @PrimaryKey(autoGenerate = true) val sessionId: Int = 0,
    val levelId: Int,
    val levelName: String,
    val startedAt: Long,
    val finishedAt: Long,
    val gradingMode: String, // MANUAL, ASSISTED, AUTO
    val totalQuestions: Int,
    val autoCorrectCount: Int,
    val partialCount: Int,
    val wrongCount: Int,
    val needReviewCount: Int,
    val autoAccuracy: Double,
    val finalAccuracy: Double,
    val rewardCoins: Int,
    val rewardExp: Int,
    val isPassed: Boolean,
    val reviewStatus: String, // NOT_NEEDED, NEED_PARENT_REVIEW, REVIEWED
    val questionResultsJson: String // JSON string serialized from List<QuestionResult>
)

data class BatchPromptStats(
    val totalProcessed: Int = 0,
    val contextClueCount: Int = 0,
    val clozeCharCount: Int = 0,
    val fullWordCount: Int = 0,
    val meaningSupplementedCount: Int = 0,
    val manualSkippedCount: Int = 0,
    val missingContextCount: Int = 0,
    val missingContextWords: List<WordItem> = emptyList()
)

@Entity(tableName = "monster_codex_entries")
data class MonsterCodexEntry(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val accountId: Long,
    val playerId: Long,
    val monsterKey: String,
    val monsterName: String,
    val monsterType: String,
    val rarity: String,
    val sourceType: String,
    val relatedWordMasked: String,
    val relatedWordFullForParent: String,
    val encounterCount: Int,
    val purifiedCount: Int,
    val bestCombo: Int,
    val bestAccuracy: Double,
    val firstEncounterAt: Long = System.currentTimeMillis(),
    val lastEncounterAt: Long = System.currentTimeMillis(),
    val isUnlocked: Boolean = false,
    val isPurified: Boolean = false
)

@Entity(tableName = "loot_drop_records")
data class LootDropRecord(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val accountId: Long,
    val playerId: Long,
    val sourceBattleId: String,
    val lootType: String, // GOLD, HATCH_ENERGY, WORD_SHARD, BRUSH_SHARD, TITLE_SHARD, JINGHUA
    val lootKey: String,
    val lootName: String,
    val amount: Int,
    val rarity: String, // COMMON, RARE, EPIC, LEGENDARY
    val createdAt: Long = System.currentTimeMillis()
)

@Entity(tableName = "achievement_records")
data class AchievementRecord(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val accountId: Long,
    val playerId: Long,
    val achievementKey: String, // e.g. first_purification, combo_3, combo_5, error_hunter_3, perfect_conquest, codex_collector_10
    val achievementName: String,
    val achievementDesc: String,
    val progressValue: Int,
    val targetValue: Int,
    val isUnlocked: Boolean = false,
    val unlockedAt: Long? = null,
    val rewardCoins: Int = 0
)

@Entity(
    tableName = "player_inventory_items",
    indices = [androidx.room.Index(value = ["playerId", "itemId"], unique = true)]
)
data class PlayerInventoryItem(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val accountId: Long,
    val playerId: Long,
    val itemId: String,
    val itemType: String, // BRUSH, AVATAR_FRAME, TITLE, PET_ACCESSORY, CAMP_THEME, MATERIAL, CONSUMABLE, etc.
    val amount: Int,
    val isOwned: Boolean = true,
    val isEquipped: Boolean = false,
    val obtainedAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)

data class ItemDefinition(
    val itemId: String,
    val itemName: String,
    val itemType: String, // BRUSH, AVATAR_FRAME, TITLE, PET_ACCESSORY, PET_TOY, CAMP_THEME, CURRENCY, MATERIAL, CONSUMABLE
    val rarity: String, // COMMON, RARE, EPIC, LEGENDARY
    val description: String,
    val priceCoins: Int = 0,
    val priceShardType: String? = null, // e.g. "BRUSH_SHARD", "WORD_SHARD", "COMBO_SHARD"
    val priceShardAmount: Int = 0,
    val unlockConditionType: String? = null, // ACHIEVE, MONSTER, PET_STAGE, NONE
    val unlockConditionValue: String? = null, // value (e.g., "combo_5", "3")
    val iconEmoji: String,
    val isConsumable: Boolean = false,
    val isEquippable: Boolean = true
) {
    companion object {
        val ALL_ITEMS = listOf(
            // --- BRUSH (书写武器) ---
            ItemDefinition(
                itemId = "default_black",
                itemName = "默认黑墨笔",
                itemType = "BRUSH",
                rarity = "COMMON",
                description = "经典的黑墨书写笔，质朴大方。",
                priceCoins = 0,
                iconEmoji = "✒️",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "practice_wood",
                itemName = "新手木杆笔",
                itemType = "BRUSH",
                rarity = "COMMON",
                description = "桃木特制的新手练习笔。",
                priceCoins = 0,
                iconEmoji = "✏️",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "ink_brush",
                itemName = "墨韵毛笔",
                itemType = "BRUSH",
                rarity = "RARE",
                description = "写字时呈现柔和粗细变化。",
                priceCoins = 300,
                iconEmoji = "🖌️",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "star_brush",
                itemName = "星尘笔",
                itemType = "BRUSH",
                rarity = "EPIC",
                description = "练习时带轻微星光轨迹。",
                priceCoins = 500,
                priceShardType = "BRUSH_SHARD",
                priceShardAmount = 5,
                iconEmoji = "✨",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "glow_brush",
                itemName = "荧光笔",
                itemType = "BRUSH",
                rarity = "RARE",
                description = "带微弱外发光，适合练习模式。",
                priceCoins = 400,
                iconEmoji = "🖍️",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "pet_brush_molong",
                itemName = "小墨龙之笔",
                itemType = "BRUSH",
                rarity = "LEGENDARY",
                description = "与小墨龙契约共鸣的书写武器。",
                priceCoins = 800,
                unlockConditionType = "PET_STAGE",
                unlockConditionValue = "50",
                iconEmoji = "🐉",
                isEquippable = true
            ),

            // --- AVATAR_FRAME (头像框) ---
            ItemDefinition(
                itemId = "frame_newbie",
                itemName = "新手勇者头像框",
                itemType = "AVATAR_FRAME",
                rarity = "COMMON",
                description = "初入字灵世界的小勇者专属头像框。",
                priceCoins = 100,
                iconEmoji = "🟢",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "frame_combo",
                itemName = "连击小勇者头像框",
                itemType = "AVATAR_FRAME",
                rarity = "RARE",
                description = "在战场中斩获连击殊荣的小勇者之冠。",
                priceCoins = 300,
                unlockConditionType = "ACHIEVE",
                unlockConditionValue = "combo_5",
                iconEmoji = "🔥",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "frame_perfect",
                itemName = "完美净化者头像框",
                itemType = "AVATAR_FRAME",
                rarity = "EPIC",
                description = "达成百步穿杨完美净化境界的黄金框。",
                priceCoins = 500,
                unlockConditionType = "ACHIEVE",
                unlockConditionValue = "perfect_conquest",
                iconEmoji = "👑",
                isEquippable = true
            ),

            // --- TITLE (称号) ---
            ItemDefinition(
                itemId = "title_newbie",
                itemName = "初出茅庐",
                itemType = "TITLE",
                rarity = "COMMON",
                description = "刚踏上听写讨伐之路的冒险新星。",
                priceCoins = 0,
                iconEmoji = "🐣",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "title_error_hunter",
                itemName = "错题猎手",
                itemType = "TITLE",
                rarity = "RARE",
                description = "追寻错字之渊、净化谬误之灵的勇者。",
                priceCoins = 0,
                unlockConditionType = "MONSTER",
                unlockConditionValue = "3",
                iconEmoji = "🏹",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "title_combo_master",
                itemName = "连击大师",
                itemType = "TITLE",
                rarity = "EPIC",
                description = "笔耕不辍，连击不绝的听写高人。",
                priceCoins = 0,
                unlockConditionType = "ACHIEVE",
                unlockConditionValue = "combo_5",
                iconEmoji = "⚡",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "title_perfect_purifier",
                itemName = "完美净化者",
                itemType = "TITLE",
                rarity = "LEGENDARY",
                description = "通关正确率100%之终极至高殊荣。",
                priceCoins = 0,
                unlockConditionType = "ACHIEVE",
                unlockConditionValue = "perfect_conquest",
                iconEmoji = "☀️",
                isEquippable = true
            ),

            // --- PET_ACCESSORY (宠物装扮) ---
            ItemDefinition(
                itemId = "pet_bell",
                itemName = "小铃铛",
                itemType = "PET_ACCESSORY",
                rarity = "COMMON",
                description = "宠物佩戴后更可爱，走路叮当响。",
                priceCoins = 200,
                iconEmoji = "🔔",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "pet_star_scarf",
                itemName = "星星围巾",
                itemType = "PET_ACCESSORY",
                rarity = "RARE",
                description = "点缀着微弱星光的舒适温暖小围巾。",
                priceCoins = 400,
                priceShardType = "WORD_SHARD",
                priceShardAmount = 10,
                iconEmoji = "🧣",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "pet_bamboo_hairpin",
                itemName = "竹叶发饰",
                itemType = "PET_ACCESSORY",
                rarity = "COMMON",
                description = "散发淡淡翠竹清香的发饰小耳挂。",
                priceCoins = 300,
                iconEmoji = "🎋",
                isEquippable = true
            ),

            // --- CAMP_THEME (营地主题) ---
            ItemDefinition(
                itemId = "theme_default",
                itemName = "默认冒险营地",
                itemType = "CAMP_THEME",
                rarity = "COMMON",
                description = "最初温馨的默认冒险帐篷营地。",
                priceCoins = 0,
                iconEmoji = "⛺",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "theme_starry_night",
                itemName = "星光夜营地",
                itemType = "CAMP_THEME",
                rarity = "EPIC",
                description = "深蓝与浪漫星空辉映的浩瀚之夜。",
                priceCoins = 600,
                iconEmoji = "🌌",
                isEquippable = true
            ),
            ItemDefinition(
                itemId = "theme_bamboo_morning",
                itemName = "竹林晨光营地",
                itemType = "CAMP_THEME",
                rarity = "EPIC",
                description = "晨曦透过翠竹洒下碎影的静谧幽谷。",
                priceCoins = 600,
                iconEmoji = "🎋",
                isEquippable = true
            )
        )
    }
}



