package com.example.util

import com.example.data.BuiltinChineseClueDictionary
import com.example.data.WordItem

object SmartPromptGenerator {

    const val STRATEGY_SMART_RECOMMEND = "SMART_RECOMMEND"               // 测验安全推荐（默认）
    const val STRATEGY_SINGLE_CHAR_CONTEXT = "SINGLE_CHAR_CONTEXT"       // 单字安全语境提示
    const val STRATEGY_TWO_CHAR_CLOZE = "TWO_CHAR_CLOZE"                 // 填空专项练习
    const val STRATEGY_ERROR_PRONE_CLOZE = "ERROR_PRONE_CLOZE"           // 易错字词填空
    const val STRATEGY_RESET_FULL_WORD = "RESET_FULL_WORD"               // 恢复完整听写
    const val STRATEGY_FILL_MEANING_ONLY = "FILL_MEANING_ONLY"           // 仅字词解释补全
    const val STRATEGY_PRACTICE_HINT_VISIBLE = "PRACTICE_HINT_VISIBLE"   // 答案可见练习模式

    fun generateSmartPrompt(
        wordItem: WordItem,
        strategy: String = STRATEGY_SMART_RECOMMEND,
        forceOverride: Boolean = false
    ): WordItem {
        // 如果已经由家长手动编辑过，且不强制覆盖，则保留
        if (wordItem.promptManuallyEdited && !forceOverride) {
            return wordItem
        }

        // 1. 查找或补全语境和字词解释
        var clueText = wordItem.clueText.ifBlank { "" }
        var meaningHint = wordItem.meaningHint.ifBlank { "" }

        val text = wordItem.text.trim()
        val len = text.length

        if (len == 1 && clueText.isBlank()) {
            val compound = CharacterCompoundDictionary.getCompoundWord(text)
            if (!compound.isNullOrBlank()) {
                clueText = compound
            }
        }

        val dictInfo = BuiltinChineseClueDictionary.getClueInfo(text)
        if (dictInfo != null) {
            if (clueText.isBlank()) clueText = dictInfo.clueText
            if (meaningHint.isBlank()) meaningHint = dictInfo.meaningHint
        }

        // 如果策略是只补充解释
        if (strategy == STRATEGY_FILL_MEANING_ONLY) {
            return wordItem.copy(
                clueText = clueText,
                meaningHint = meaningHint,
                promptAutoGenerated = true,
                promptQuality = if (clueText.isNotBlank() || meaningHint.isNotBlank()) "GOOD" else "NEED_CONTEXT"
            )
        }

        // 答案可见练习模式（仅用于练习跟写，标注 PRACTICE_HINT）
        if (strategy == STRATEGY_PRACTICE_HINT_VISIBLE) {
            val visible = if (clueText.isNotBlank()) "$clueText ($text)" else text
            return wordItem.copy(
                promptMode = if (len == 1 && clueText.isNotBlank()) "CONTEXT_CLUE" else "FULL_WORD",
                hiddenIndicesStr = "",
                visiblePrompt = visible,
                ttsPrompt = if (clueText.isNotBlank()) "请写“${clueText}”的“${text}”" else "请写词语：$text",
                targetAnswer = text,
                clueText = clueText,
                meaningHint = meaningHint,
                visibilityPolicy = PromptSecurityUtil.POLICY_PRACTICE_HINT,
                promptAutoGenerated = true,
                promptQuality = "GOOD"
            )
        }

        // 如果策略是全部重置为完整听写
        if (strategy == STRATEGY_RESET_FULL_WORD) {
            return wordItem.copy(
                promptMode = "FULL_WORD",
                hiddenIndicesStr = "",
                visiblePrompt = "请根据语音写出词语",
                ttsPrompt = if (len == 1) "请写汉字：“$text”" else "请写词语：“$text”",
                targetAnswer = text,
                clueText = clueText,
                meaningHint = meaningHint,
                visibilityPolicy = PromptSecurityUtil.POLICY_TEST_SAFE,
                promptAutoGenerated = true,
                promptQuality = "GOOD"
            )
        }

        // 下面均为正式测验安全（TEST_SAFE）模式规则

        // 单字处理（len == 1）
        if (len == 1) {
            val isContextStrategy = strategy == STRATEGY_SMART_RECOMMEND || strategy == STRATEGY_SINGLE_CHAR_CONTEXT
            return if (isContextStrategy && clueText.isNotBlank()) {
                val maskedVisible = PromptSecurityUtil.maskTargetAnswerInPrompt(clueText, text)
                wordItem.copy(
                    promptMode = "CONTEXT_CLUE",
                    hiddenIndicesStr = "0",
                    visiblePrompt = maskedVisible,
                    ttsPrompt = "请写“${clueText}”的“${text}”",
                    targetAnswer = text,
                    contextText = clueText,
                    clueText = clueText,
                    meaningHint = meaningHint,
                    visibilityPolicy = PromptSecurityUtil.POLICY_TEST_SAFE,
                    promptAutoGenerated = true,
                    promptQuality = "GOOD"
                )
            } else {
                wordItem.copy(
                    promptMode = "FULL_WORD",
                    hiddenIndicesStr = "",
                    visiblePrompt = "请根据语音写出词语",
                    ttsPrompt = "请写汉字：“${text}”",
                    targetAnswer = text,
                    clueText = clueText,
                    meaningHint = meaningHint,
                    visibilityPolicy = PromptSecurityUtil.POLICY_TEST_SAFE,
                    promptAutoGenerated = true,
                    promptQuality = if (clueText.isBlank()) "NEED_CONTEXT" else "GOOD"
                )
            }
        }

        // 填空专项练习（仅显式指定填空策略，或易错字填空）
        val shouldCloze = strategy == STRATEGY_TWO_CHAR_CLOZE ||
                (strategy == STRATEGY_ERROR_PRONE_CLOZE && wordItem.difficulty == "易错")

        if (shouldCloze && len >= 2) {
            val clozeVisible = "__${text.drop(1)}"
            return wordItem.copy(
                promptMode = "CLOZE_CHAR",
                hiddenIndicesStr = "0",
                visiblePrompt = clozeVisible,
                ttsPrompt = "请写“${text}”的第一个字",
                targetAnswer = text.take(1),
                clueText = clueText,
                meaningHint = meaningHint,
                visibilityPolicy = PromptSecurityUtil.POLICY_TEST_SAFE,
                promptAutoGenerated = true,
                promptQuality = "GOOD"
            )
        }

        // 两字词、三字词、四字成语及其他：默认 SMART_RECOMMEND 保持 FULL_WORD
        val defaultTts = if (len == 4) "请写成语：$text" else "请写词语：$text"
        val defaultVisible = if (len == 4) "请根据语音写出成语" else "请根据语音写出词语"

        return wordItem.copy(
            promptMode = "FULL_WORD",
            hiddenIndicesStr = "",
            visiblePrompt = defaultVisible,
            ttsPrompt = defaultTts,
            targetAnswer = text,
            clueText = clueText,
            meaningHint = meaningHint,
            visibilityPolicy = PromptSecurityUtil.POLICY_TEST_SAFE,
            promptAutoGenerated = true,
            promptQuality = "GOOD"
        )
    }
}
